# Generated by Django 3.0.6 on 2020-06-16 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='first-post', unique=True),
            preserve_default=False,
        ),
    ]
